-- ==========================================
-- SMART APPOINTMENT - DATABASE SCHEMA
-- ==========================================

-- 1. PROFILES & AUTH
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  full_name TEXT,
  avatar_url TEXT,
  role TEXT CHECK (role IN ('admin', 'doctor', 'patient', 'superuser')) DEFAULT 'patient',
  phone TEXT,
  date_of_birth DATE
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Safety check for policies
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public profiles are viewable by everyone.') THEN
        CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update their own profile.') THEN
        CREATE POLICY "Users can update their own profile." ON profiles FOR UPDATE USING (auth.uid() = id);
    END IF;
END $$;

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url', 
    CASE 
      WHEN new.email = 'smart@gmail.com' THEN 'superuser'
      ELSE COALESCE(new.raw_user_meta_data->>'role', 'patient')
    END
  );

  -- Make sure superusers and doctors are added to the doctors table
  IF new.email = 'smart@gmail.com' OR COALESCE(new.raw_user_meta_data->>'role', '') IN ('doctor', 'admin') THEN
    INSERT INTO public.doctors (id, is_available, rating, experience_years)
    VALUES (new.id, true, 5.0, 10);
  END IF;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. SPECIALTIES & DOCTORS
CREATE TABLE IF NOT EXISTS specialties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT,
  description TEXT
);

CREATE TABLE IF NOT EXISTS doctors (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  specialty_id BIGINT REFERENCES specialties(id),
  bio TEXT,
  experience_years INT,
  rating DECIMAL DEFAULT 5.0,
  is_available BOOLEAN DEFAULT true
);

ALTER TABLE specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Specialties are viewable by everyone') THEN
        CREATE POLICY "Specialties are viewable by everyone" ON specialties FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Doctors are viewable by everyone') THEN
        CREATE POLICY "Doctors are viewable by everyone" ON doctors FOR SELECT USING (true);
    END IF;
END $$;


-- 3. APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  patient_id UUID REFERENCES profiles(id) NOT NULL,
  doctor_id UUID REFERENCES doctors(id) NOT NULL,
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  status TEXT CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show')) DEFAULT 'scheduled',
  reason TEXT,
  notes TEXT
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Patients can view own appointments') THEN
        CREATE POLICY "Patients can view own appointments" ON appointments FOR SELECT USING (auth.uid() = patient_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Patients can book appointments') THEN
        CREATE POLICY "Patients can book appointments" ON appointments FOR INSERT WITH CHECK (auth.uid() = patient_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Doctors can view assigned appointments') THEN
        CREATE POLICY "Doctors can view assigned appointments" ON appointments FOR SELECT USING (auth.uid() = doctor_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Doctors can update assigned appointments') THEN
        CREATE POLICY "Doctors can update assigned appointments" ON appointments FOR UPDATE USING (auth.uid() = doctor_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Patients can update own appointments') THEN
        CREATE POLICY "Patients can update own appointments" ON appointments FOR UPDATE USING (auth.uid() = patient_id);
    END IF;
END $$;


-- 4. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  sender_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT CHECK (type IN ('system', 'appointment', 'message', 'alert')) DEFAULT 'system',
  is_read BOOLEAN DEFAULT false,
  metadata JSONB
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own notifications') THEN
        CREATE POLICY "Users can view own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins/Doctors can send notifications') THEN
        CREATE POLICY "Admins/Doctors can send notifications" ON notifications FOR INSERT WITH CHECK (
          EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'doctor'))
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Patients can send appointment notifications') THEN
        CREATE POLICY "Patients can send appointment notifications" ON notifications FOR INSERT WITH CHECK (
          type = 'appointment'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own notifications') THEN
        CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (auth.uid() = user_id);
    END IF;
END $$;


-- 5. WAYFINDING
CREATE TABLE IF NOT EXISTS hospital_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  building TEXT DEFAULT 'Main',
  floor INT,
  room_number TEXT,
  department TEXT,
  coordinates_x INT,
  coordinates_y INT
);

ALTER TABLE hospital_locations ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Locations are viewable by everyone') THEN
        CREATE POLICY "Locations are viewable by everyone" ON hospital_locations FOR SELECT USING (true);
    END IF;
END $$;


-- 6. SEED DATA
INSERT INTO specialties (name, icon, description) 
VALUES 
  ('Cardiology', 'Heart', 'Heart and blood vessel specialists'),
  ('Pediatrics', 'Baby', 'Medical care for infants and children')
ON CONFLICT (name) DO NOTHING;

-- 7. RPC FUNCTIONS
-- This function allows admins to securely delete a user from the client app.
CREATE OR REPLACE FUNCTION delete_user(target_user_id UUID)
RETURNS void AS $$
BEGIN
  -- Check if the current user has admin privileges
  IF NOT EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() AND role IN ('admin', 'superuser')
  ) THEN
    RAISE EXCEPTION 'Unauthorized: Only admins can delete users.';
  END IF;

  -- Delete related records first to avoid foreign key violations
  DELETE FROM appointments WHERE patient_id = target_user_id OR doctor_id = target_user_id;
  DELETE FROM notifications WHERE user_id = target_user_id OR sender_id = target_user_id;
  
  -- Delete the user from auth.users (this will cascade to profiles and doctors)
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
